# Your Name or Company
title: LISA CARUSO

# Description of your website. This is used for social sharing.
description:

# A brief blurb about yourself
content:

# Add your social links
social:
  - platform: Spotify
    url: https://open.spotify.com/artist/36HJno2GZYrC3jPO8ACz6T
  - platform: Apple Music
    url: https://music.apple.com/au/artist/lisa-caruso/924280947
  - platform: Bandcamp
    url: https://lisacarusomusic.bandcamp.com/
  - platform: YouTube
    url: https://www.youtube.com/channel/UC_YSOFnJyYBLLai-Ni3BckA
  - platform: Facebook
    url: https://www.facebook.com/lisacarusomusic/
  - platform: Instagram
    url: https://www.instagram.com/lisacaruso/
  - platform: Email
    url: mailto:lisacarusomusic@gmail.com

# General settings
url: https://lisacaruso.com.au
baseurl: "" 
markdown: kramdown
sharing_image: full-lg.jpg
google_analytics: "" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: center # left, right or center

theme: jekyll-theme-cayman
