# Your Name or Company
title: Lisa Caruso

# Description of your website. This is used for social sharing.
description:

# A brief blurb about yourself
content:

# Add your social links
social:
  - platform: spotify
    url: https://open.spotify.com/artist/36HJno2GZYrC3jPO8ACz6T
  - platform: youtube
    url: https://www.youtube.com/channel/UC_YSOFnJyYBLLai-Ni3BckA
  - platform: instagram
    url: https://www.instagram.com/lisacaruso/

# General settings
url: https://dyor.lol
baseurl: "" 
markdown: kramdown
sharing_image: full-lg.jpg
google_analytics: "" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: center # left, right or center

theme: jekyll-theme-cayman
