# Your Name or Company
title: LISA <br>CARUSO

# Description of your website. This is used for social sharing.
description:

# A brief blurb about yourself
content:

# Add your social links
social:
  - platform: Listen on Spotify
    url: https://open.spotify.com/artist/36HJno2GZYrC3jPO8ACz6T

# General settings
url: https://dyor.lol
baseurl: "" 
markdown: kramdown
sharing_image: full-lg.jpg
google_analytics: "" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: center # left, right or center

theme: jekyll-theme-cayman
